package dev.sumanth.spd.ui.theme
import androidx.compose.ui.graphics.Color

// ============= MODERN PREMIUM COLOR PALETTE =============
// Primary: Vibrant Blue-Purple Gradient
val primaryLight = Color(0xFF5B4FB8)      // Vibrant Purple
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFEADFFF)
val onPrimaryContainerLight = Color(0xFF3D2D7A)

// Secondary: Emerald Green - Accent
val secondaryLight = Color(0xFF4CAF91)    // Modern Teal
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0F8E8)
val onSecondaryContainerLight = Color(0xFF005C47)

// Tertiary: Warm Golden - Highlight
val tertiaryLight = Color(0xFFB8860B)     // Goldenrod
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFE8C1)
val onTertiaryContainerLight = Color(0xFF6B4E00)

// Error: Soft Red
val errorLight = Color(0xFFD32F2F)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFEAEA)
val onErrorContainerLight = Color(0xFF6B0000)

// Backgrounds & Surfaces - Clean & Minimal
val backgroundLight = Color(0xFFFAFAFA)
val onBackgroundLight = Color(0xFF1A1A1A)
val surfaceLight = Color(0xFFFAFAFA)
val onSurfaceLight = Color(0xFF1A1A1A)
val surfaceVariantLight = Color(0xFFEEEEEE)
val onSurfaceVariantLight = Color(0xFF4A4A4A)
val outlineLight = Color(0xFF989898)
val outlineVariantLight = Color(0xFFD0D0D0)
val scrimLight = Color(0xFF000000)

// Inverse & Dim
val inverseSurfaceLight = Color(0xFF2D2D2D)
val inverseOnSurfaceLight = Color(0xFFF5F5F5)
val inversePrimaryLight = Color(0xFFD0C4FF)
val surfaceDimLight = Color(0xFFE8E8E8)
val surfaceBrightLight = Color(0xFFFAFAFA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F5F5)
val surfaceContainerLight = Color(0xFFEFEFEF)
val surfaceContainerHighLight = Color(0xFFEAEAEA)
val surfaceContainerHighestLight = Color(0xFFE4E4E4)

// ============= MEDIUM CONTRAST VARIANTS =============
val primaryLightMediumContrast = Color(0xFF3D2D7A)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF7466D4)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF2D7964)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF62C89D)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF805A00)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFC9941C)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFFA71D1D)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFE55555)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFAFAFA)
val onBackgroundLightMediumContrast = Color(0xFF1A1A1A)
val surfaceLightMediumContrast = Color(0xFFFAFAFA)
val onSurfaceLightMediumContrast = Color(0xFF1A1A1A)
val surfaceVariantLightMediumContrast = Color(0xFFEEEEEE)
val onSurfaceVariantLightMediumContrast = Color(0xFF3A3A3A)
val outlineLightMediumContrast = Color(0xFF7A7A7A)
val outlineVariantLightMediumContrast = Color(0xFFAEAEAE)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2D2D2D)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF5F5F5)
val inversePrimaryLightMediumContrast = Color(0xFFD0C4FF)
val surfaceDimLightMediumContrast = Color(0xFFE8E8E8)
val surfaceBrightLightMediumContrast = Color(0xFFFAFAFA)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF5F5F5)
val surfaceContainerLightMediumContrast = Color(0xFFEFEFEF)
val surfaceContainerHighLightMediumContrast = Color(0xFFEAEAEA)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE4E4E4)

// ============= HIGH CONTRAST VARIANTS =============
val primaryLightHighContrast = Color(0xFF20136D)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF3D2D7A)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF0D503D)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF2D7964)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF563900)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF805A00)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF740004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFFA71D1D)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFAFAFA)
val onBackgroundLightHighContrast = Color(0xFF000000)
val surfaceLightHighContrast = Color(0xFFFAFAFA)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEEEEEE)
val onSurfaceVariantLightHighContrast = Color(0xFF1A1A1A)
val outlineLightHighContrast = Color(0xFF3A3A3A)
val outlineVariantLightHighContrast = Color(0xFF3A3A3A)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2D2D2D)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFF9FD)
val surfaceDimLightHighContrast = Color(0xFFE8E8E8)
val surfaceBrightLightHighContrast = Color(0xFFFAFAFA)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF5F5F5)
val surfaceContainerLightHighContrast = Color(0xFFEFEFEF)
val surfaceContainerHighLightHighContrast = Color(0xFFEAEAEA)
val surfaceContainerHighestLightHighContrast = Color(0xFFE4E4E4)

// ============= DARK THEME COLORS =============
// Dark Mode - Premium & Modern
val primaryDark = Color(0xFFD0C4FF)       // Light Purple
val onPrimaryDark = Color(0xFF3D2D7A)
val primaryContainerDark = Color(0xFF5B4FB8)
val onPrimaryContainerDark = Color(0xFFEADFFF)

val secondaryDark = Color(0xFFB3E5CC)     // Light Teal
val onSecondaryDark = Color(0xFF005C47)
val secondaryContainerDark = Color(0xFF297962)
val onSecondaryContainerDark = Color(0xFFD0F8E8)

val tertiaryDark = Color(0xFFFFD699)      // Light Gold
val onTertiaryDark = Color(0xFF6B4E00)
val tertiaryContainerDark = Color(0xFF8F6F1D)
val onTertiaryContainerDark = Color(0xFFFFE8C1)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

// Dark Backgrounds - Deep & Clean
val backgroundDark = Color(0xFF121212)
val onBackgroundDark = Color(0xFFE8E8E8)
val surfaceDark = Color(0xFF121212)
val onSurfaceDark = Color(0xFFE8E8E8)
val surfaceVariantDark = Color(0xFF49454E)
val onSurfaceVariantDark = Color(0xFFCAC7D0)
val outlineDark = Color(0xFF948F99)
val outlineVariantDark = Color(0xFF49454E)
val scrimDark = Color(0xFF000000)

// Dark Inverse & Dim
val inverseSurfaceDark = Color(0xFFF0DFD7)
val inverseOnSurfaceDark = Color(0xFF382E29)
val inversePrimaryDark = Color(0xFF5B4FB8)
val surfaceDimDark = Color(0xFF121212)
val surfaceBrightDark = Color(0xFF3A3A3C)
val surfaceContainerLowestDark = Color(0xFF0D0D0D)
val surfaceContainerLowDark = Color(0xFF1A1A1C)
val surfaceContainerDark = Color(0xFF1E1E20)
val surfaceContainerHighDark = Color(0xFF292929)
val surfaceContainerHighestDark = Color(0xFF343434)

// Dark Medium Contrast
val primaryDarkMediumContrast = Color(0xFFD5CAFF)
val onPrimaryDarkMediumContrast = Color(0xFF1F0E5C)
val primaryContainerDarkMediumContrast = Color(0xFFA89DD8)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFB8E9D1)
val onSecondaryDarkMediumContrast = Color(0xFF003D31)
val secondaryContainerDarkMediumContrast = Color(0xFF7ECBA7)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFDD9B)
val onTertiaryDarkMediumContrast = Color(0xFF4A3500)
val tertiaryContainerDarkMediumContrast = Color(0xFFD9B84D)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF121212)
val onBackgroundDarkMediumContrast = Color(0xFFE8E8E8)
val surfaceDarkMediumContrast = Color(0xFF121212)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF49454E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD0CDD7)
val outlineDarkMediumContrast = Color(0xFFADA8B2)
val outlineVariantDarkMediumContrast = Color(0xFF8D8895)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFF0DFD7)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF312823)
val inversePrimaryDarkMediumContrast = Color(0xFF4238A8)
val surfaceDimDarkMediumContrast = Color(0xFF121212)
val surfaceBrightDarkMediumContrast = Color(0xFF3A3A3C)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0D0D0D)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1A1C)
val surfaceContainerDarkMediumContrast = Color(0xFF1E1E20)
val surfaceContainerHighDarkMediumContrast = Color(0xFF292929)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF343434)

// Dark High Contrast
val primaryDarkHighContrast = Color(0xFFFFF9FD)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD5CAFF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFEBFBF4)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB8E9D1)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFF9F0)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFDD9B)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF121212)
val onBackgroundDarkHighContrast = Color(0xFFFFFFFF)
val surfaceDarkHighContrast = Color(0xFF121212)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF49454E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFBFE)
val outlineDarkHighContrast = Color(0xFFD0CDD7)
val outlineVariantDarkHighContrast = Color(0xFFD0CDD7)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFF0DFD7)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF3A2A84)
val surfaceDimDarkHighContrast = Color(0xFF121212)
val surfaceBrightDarkHighContrast = Color(0xFF3A3A3C)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0D0D0D)
val surfaceContainerLowDarkHighContrast = Color(0xFF1A1A1C)
val surfaceContainerDarkHighContrast = Color(0xFF1E1E20)
val surfaceContainerHighDarkHighContrast = Color(0xFF292929)
val surfaceContainerHighestDarkHighContrast = Color(0xFF343434)







