name: Build
on:
  push:
    branches:
      - 'main'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Access Api keys
        env:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          path: app/src/main/res/values/secrets.xml
        run: |
          touch $path
          echo \<resources\> >> $path
          echo \<string name=\"CLIENT_ID\"\>$clientId\</string\> >> $path
          echo \<string name=\"CLIENT_SECRET\"\>$clientSecret\</string\> >> $path
          echo \</resources\> >> $path

      - name: Build Debug APK
        id: build
        run: bash ./gradlew assembleDebug
